name: Setup Environment
description: Setups the environment like installing golang and protoc

runs:
  using: "composite"
  steps:
  - name: Setup Protobuf
    uses: wizhi/setup-buf@v1
    with:
      version: '0.36.0'

  - name: Setup Proto compiler
    uses: arduino/setup-protoc@v1
    with:
      version: '3.x'

  - name: Setup Go environment
    uses: actions/setup-go@v5.0.2
    
  - name: Install proto-gen-go
    shell: bash
    run: |
      go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

  - name: Generate code from proto definitions
    shell: bash
    run: make -C src/proto go

  - uses: actions/setup-node@v3
    with:
      node-version: 16

  - name: Install dotenvx
    run: curl -sfS https://dotenvx.sh/install.sh | sh
    shell: bash