run-name: Build container image and push to GitHub Packages
on:
  push:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: quikkom/auth
jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout

      - name: Read version number
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ steps.version.outputs.content }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}