name: Container Image Build
run-name: Build container image and push to GitHub Packages
on:
  push:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: quikkom/auth
jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
      
    runs-on: ubuntu-latest
    services:
      # Start a postgresql instance to run tests
      postgresql:
        image: postgres:16.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          submodules: true # Get proto repository too

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Create .env file
        run: |
          cat << EOF > .env
          DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
          AUTH_SECRET="auth_secret"
          EOF
      - name: Run tests
        working-directory: ./src
        run: dotenvx -f ../.env -- go test -v

      - name: Read version number
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ steps.version.outputs.content }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Bump version
        uses: remorses/bump-version@js
        with:
            version_file: ./VERSION
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}