name: container-image-build
run-name: Build container image and push to GitHub Packages
on:
  merge_group:
    
  push:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: quikkom/auth
jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          submodules: true # Get proto repository too

      - name: Setup Protobuf
        uses: wizhi/setup-buf@v1
        with:
          version: '0.36.0'

      - name: Setup Proto compiler
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2

      - name: Install proto-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Generate code from proto definitions
        run: make -C src/proto go

      - name: Read version number
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ steps.version.outputs.content }}